blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/atulyaai/Atulya-Cpanel/discussions
    about: Please use Discussions for Q&A and general support.


